## Numerical Analysis - Fall semester 2025
# Serie 01 - Scientific computing with Python

This notebook serves as a brief introduction to the programming language [Python](https://www.python.org/). If you are already very familiar with Python, [Jupyter notebooks](https://jupyter.org/), and the [NumPy](https://numpy.org/) and [Matplotlib](https://matplotlib.org/) packages, you may skip the explanations and directly attempt the exercises below the green boxes &#x1F7E9;.

<hr style="clear:both">

### Jupyter notebooks for mixing text with code

A Jupyter notebook is a useful tool for mixing text with code. Each notebook is made up of multiple cells stacked on top of each other. Cells can be added, deleted, and rearranged. Each cell contains either some text which is formatted with Markdown (what you are reading now) or some code which is interpreted with the Python language.

<div class="alert alert-info">

**Note:** You can run the code in Python cells by clicking on them and pressing `Ctrl+Enter` or `Shift+Enter`.
</div>

The `print` function can be used to display text or numbers below a Python cell.

In [ ]:
print("Hello World!")  # prints "Hello World!" below this Python cell
print(42)  # prints '42' below this Python cell

<div class="alert alert-info">

**Note:** You can add cells to this notebook by clicking on any cell and pressing `B` or the `+` icon in the navigation bar. This allows you to try out your own code and will be particularly useful for solving the exercises.
</div>

<hr style="clear:both">

### Basic Python functionalities 

Most of you have already written code in the Python language before. Therefore, we will just quickly review the features of Python which you will need throughout the course. If you have never worked with Python before, you can refer to [The Python Tutorial](https://docs.python.org/3/tutorial/index.html) to fill in the details.

**Variables** can memorize a number, a list, or other objects for later use. They can be a combination of letters (`a-z`, `A-Z`), numbers (`0-9`, but not as the first character), and underscores (`_`). You can assign to a variable using the `=` operator.

In [ ]:
x = 5  # define a variable
y = x - 3  # define a variable based on another variable
data = [5, 2, 7, 1]  # define a list

<div class="alert alert-info">

**Note:** A variable defined in one cell can be accessed from any other cells, after the cell has been run. However, a variable should not be used in cells located above the cell where it is defined, since this variable will not be known when the cells in your notebook are ran from top to bottom, which will be the case when other people try to reproduce your results.
</div>

You can access the elements or slices of a list using square brackets `[]`.

<div class="alert alert-warning">
    
**Warning:** In Python, unlike in some other scientific programming languages (MATLAB, Fortran, Julia, and R), the index of the first element in a list is `0`.
</div>

In [ ]:
print(data[1])  # second element
print(data[1:])  # all elements starting from the second
print(data[1:3])  # all elements between the second and fourth
print(data[-1])  # the last element
print(len(data))  # the number of elements

**Mathematical operations** allow you to manipulate numbers and/or variables.

In [ ]:
print(x + y)  # addition
print(x - y)  # subtraction
print(x * y)  # multiplication
print(x / y)  # division
print(x % y)  # Modulus (remainder)
print(x ** y)  # Exponentiation

**Comparison operators** help determine relations between two variables.

In [ ]:
print(x > y)  # greater than
print(x >= y)  # greater than or equal
print(x == y)  # equal
print(x <= y)  # smaller than or equal
print(x < y)  # smaller than

**If/elif/else**-clauses and **for**-loops help control the flow of a Python program. Notice the use of colons `:` after each statement, and that code blocks in Python must be indented.

To demonstrate these statements, we write a small code-block which loops over all numbers from $0$ to $4$ and prints whether these numbers are smaller, equal, or greater than $2$.

<div class="alert alert-info">

**Note:** Oftentimes, we will need to iterate through a range of numbers. In Python, this can be done with the `range` function. For two integers `a` and `b`, `range(a, b)` iterates through `[a, a+1, ..., b-2, b-1]`. If no starting point is specified, the range automatically starts at `0`, such that `range(5) -> [0, 1, 2, 3, 4]`.
</div>

In [ ]:
for i in range(5):
    if i < 2:
        print(f"{i} is smaller than 2")
    elif i == 2:
        print(f"{i} is equal to 2")
    else:  # i > 2
        print(f"{i} is greater than 2")

**Functions** can be thought of as code blocks which can be run on demand. They are a nice way of keeping your code readable and organized, and help avoiding code repetitions. They are defined with the `def` keyword. Again, indentation is mandatory. You can define an output (or multiple outputs separated by commas) of a function using the `return` keyword. During execution, once a `return` is encountered, the function is exited immediately and the remaining code in the function is not run.

As an example, we define a function which returns all *real* solutions $x$ to the equality
$$
    a x^2 + b x + c = 0
$$
for $a \neq 0$.

In [ ]:
def solve_quadratic_equation(a, b, c):
    """ finds all real x such that a * x ** 2  + b * x + c = 0 when a =/= 0 """
    discriminant = b ** 2 - 4 * a * c
    if discriminant > 0:
        x_1 = (- b - (discriminant) ** (1 / 2)) / (2 * a)
        x_2 = (- b + (discriminant) ** (1 / 2)) / (2 * a)
        return x_1, x_2
    elif discriminant == 0:
        x = - b / (2 * a)
        return x
    else:  # discriminant < 0 (only complex solutions)
        return None

We may then call the function we have just defined for different function arguments.

In [ ]:
print(f"the real solution/s to 4 * x ** 2 - 1 = 0 is/are x = {solve_quadratic_equation(4, 0, -1)}")
print(f"the real solution/s to x ** 2 - 2 * x + 1 = 0 is/are x = {solve_quadratic_equation(1, -2, 1)}")

To quickly check if a function works as expected, we will use the `assert` keyword. An assertion does nothing if a condition is verified, but prints an "error" message if the condition is violated.

In [ ]:
assert (x := solve_quadratic_equation(1, 0, 0)) == 0, f"the solution to x ** 2 = 0 should be 0, but got {x} instead"
assert (x := solve_quadratic_equation(1, 0, 1)) == None, f"there exists no solution to x ** 2 + 1 = 0, but got {x} instead"

<div class="alert alert-success">
    
**Exercise 1:** In the below cell, complete the `fibonacci` function which takes as input a natural number $n$ and returns the $n$-th Fibonacci number $F_n$, which is defined as
$$
F_n = \begin{cases} 0, & \text{if $n = 0$} \\ 1, & \text{if $n = 1$} \\ F_{n-1} + F_{n-2}, & \text{if $n \geq 2$} \end{cases}
$$
*Hint:* There are many ways in which you can solve this problem. For example by calling the `fibonacci` function recursively, or by generating the Fibonacci numbers in ascending order, starting from the two smallest $F_0$ and $F_1$.
</div>


In [ ]:
def fibonacci(n):
    """ returns the n-th Fibonacci number """

    if n < 2:  # Return first two Fibonacci numbers F_0 = 0 and F_1 = 1 directly
        return n

    # YOUR CODE HERE
    raise NotImplementedError()

Let's run your function implementation through some basic tests, to see if it works as expected.

In [ ]:
assert not (fibonacci(1) is None), f"'fibonacci(1)' returned nothing, make sure to 'return' your result"; assert isinstance(fibonacci(1), int), f"expected 'fibonacci' to return an integer, but got {type(fibonacci(1))}"; assert (F := fibonacci(0)) == 0, f"'fibonacci(0)' should return 0, but got {F}"; assert (F := fibonacci(1)) == 1, f"'fibonacci(1)' should return 1, but got {F}"; assert (F := fibonacci(2)) == 1, f"'fibonacci(2)' should return 1, but got {F}"; assert (F := fibonacci(3)) == 2, f"'fibonacci(3)' should return 2, but got {F}"; assert (F := fibonacci(5)) == 5, f"'fibonacci(5)' should return 5, but got {F}"; assert (F := fibonacci(9)) == 34, f"'fibonacci(9)' should return 34, but got {F}"; print("Great job! It seems like your function works correctly.")

**Loop** You can loop over the elements of a list like this

In [1]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


If you want access to the index of each element within the body of a loop, use the built-in enumerate function:

In [2]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print(idx + 1, animal)

1 cat
2 dog
3 monkey


**List comprehensions**: When programming, frequently we want to transform one type of data
into another. As a simple example, consider the following code that computes square numbers:

In [3]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
    print(squares)

[0]
[0, 1]
[0, 1, 4]
[0, 1, 4, 9]
[0, 1, 4, 9, 16]


You can make this code simpler using a list comprehension:

In [4]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

[0, 4, 16]


<hr style="clear:both">

### The `numpy` package for scientific computing

Particularly when manipulating large amounts of data, the basic Python functionalities can be very slow and restrictive. To illustrate this, let us consider a simple example: the cumulative sum of a list, i.e. the list which contains the sum of all previous entries of an input list.
$$
\mathrm{cumsum}([1, 2, 3, 4, 5]) = [1, 3, 6, 10, 15]
$$

In [ ]:
def cumsum(input_list):
    """ computes the cumulative sum of the input list """
    
    cumsum_now = 0  # stores the current cumulative sum
    cumsum_list = []  # stores all cumulative sums
    for entry in input_list:  # iterate through all the entries of the input list
        cumsum_now = cumsum_now + entry  # add the entry to the current cumulative sum
        cumsum_list.append(cumsum_now)  # append the current cumulative sum
    return cumsum_list

Let's time it using the `%timeit` Jupyter notebook magic command. This will run the function multiple times, and tell us the average runtime.

In [ ]:
%timeit -n 10 cumsum(range(1_000_000))

That took quite some time... We will now use the NumPy package to speed up this operation. To use a package, we will need to use the `import` keyword. Often, the `as` keyword is used to save the package to a more convenient variable, as to avoid having to write `numpy` whenever we want to use a function from this package. On Noto, many packages are already installed and can simply be imported. If you are working locally, you'll need to [install packages manually](https://packaging.python.org/en/latest/tutorials/installing-packages/).

In [6]:
import numpy as np

<div class="alert alert-info">

**Note:** After restarting your notebook, you will always have to re-run the cell where you import the package(s) you want to use.
</div>

Conveniently, the `cumsum` function is already implemented in the NumPy package. There is also a "faster" alternative to the `range` function in NumPy: `np.arange`.

In [ ]:
%timeit -n 10 np.cumsum(np.arange(1_000_000))

Wow! With NumPy it is so simple and *a lot* faster. This is why we will make sure to work with NumPy wherever we can. Furthermore, NumPy has a lot of specialized functions designed for scientific computing. In fact, there are thousands, and it is almost impossible to keep track of all of them. You can find them in [NumPy documentation](https://numpy.org/doc/stable/reference/routines.html). Below we summarize some of the functions which you are most likely going to use or encounter at some point during this course.

**NumPy arrays** are the underlying array object in NumPy. They can be used to store vectors, matrices, and much more.

In [ ]:
print(np.array([1, 2, 5]))  # vector of size 3 with entries 1, 2, 5
print(np.arange(2, 6))  # vector with all integers starting from 2 and ending before 6
print(np.linspace(0, 1, 5))  # vector with 5 evenly spaced values between 0 and 1
print(np.zeros(4))  # zero-vector of size 4
print(np.ones(2))  # vector of ones of size 2

All the above commands also work for defining matrices of various shapes.

<div class="alert alert-warning">
    
**Warning:** To define a matrix of zeros or ones, you will have to input its shape as a list `np.zeros([2, 2])` and not as separate arguments `np.zeros(2, 2)`. 
</div>

In [ ]:
print(np.array([[1, -1], [2, 2]]))  # 2x2 matrix with rows [1, -1] and [2, 2]
print(np.zeros([2, 4]))  # 2x4 zero-matrix
print(np.ones([3, 3]))  # 3x3 matrix of ones
print(np.eye(3))  # 3x3 identity matrix

There are also commands which are particularly useful for designing mathematical matrices.

In [ ]:
print(np.eye(3))  # 3x3 identity matrix 
print(np.diag([1, 2, 3]))  # diagonal matrix with diagonal elements [1, 2, 3]
print(np.diag([1, 2, 3], k=1))  # matrix with elements [1, 2, 3] on first off-diagonal 

NumPy arrays can be stored as variables. Accessing elements or slices of NumPy arrays works just like it did with lists. But with NumPy arrays, we can also access elements by using arrays of indices.

In [ ]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])  # some 2x4 array
print(A)
print(A[0, 1])  # element in first row, second column
print(A[:, :2])  # first two columns
print(A[np.array([0, 1]), np.array([2, 3])])  # entries at first row, third column; and second row, fourth column

This also allows us to easily redefine certain entries or slices of NumPy arrays.

In [ ]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])  # some 2x4 array
print(A)
A[:, 0] = 0  # set first column of array to zero
print(A)
A[0, 1:4] = np.array([5, 5, 5])  # set second to fourth entry to [5, 4, 3]
print(A)
A[np.array([0, 1]), np.array([2, 3])] = np.array([3, 3])  # set (0, 2) to 3 and (1, 3) element to 3
print(A)

NumPy array can easily be manipulated and analyzed using various methods, which are accessed with the dot (`.`) operator.

In [ ]:
print(A.T)  # transpose
print(A.flatten())  # put rows of matrix into a vector
print(A.max())  # maximum element
print(A.sum())  # sum of all elements

<div class="alert alert-warning">
    
**Warning:** The array methods, accessed with a dot (`.`), usually *won't* change the array they are used on itself, but will instead return the resulting array as a copy, which we can assign to another variable. 
</div>

In [ ]:
A_clipped = A.clip(3)  # returns an array where all values smaller than 3 are replaced by 3
print(A)  # original array
print(A_clipped)  # clipped array

We can also retrieve and manipulate the shape of an array.

In [ ]:
print(A.shape)  # shape of array
print(A.reshape([4, 2]))  # change 2x4 array to 4x2 array
print(A.reshape([1, -1]))  # change 2x4 array to 1x(everything else) array (similar to '.flatten()')

We can stack and combine NumPy arrays to generate a new array from two or more existing arrays.

In [ ]:
x = np.array([1, 2, 3])  # some length 3 vector
print(x)  # original vector
print(np.append(x, x))  # append a vector to itself
print(np.concatenate([A, A, A], axis=0))  # vertically stack a matrix three times
print(np.concatenate([A, A, A], axis=1))  # horizontally stack a matrix three times

<div class="alert alert-info">

**Note:** The `axis` argument in the `np.concatenate` function specifies along which dimension the arrays are stacked: `axis=0` stacks them vertically (column-wise), while `axis=1` stacks them horizontally (row-wise).
</div>

<div class="alert alert-success">
    
**Exercise 2:** Given a length $n \in \mathbb{N}$ NumPy array $c$, write a function which returns its *companion matrix*, i.e. the $n \times n$ NumPy array
$$C = \begin{pmatrix} 0 & 0 &  \dots & 0 & -c[0] \\ 1 & 0 &  \dots & 0 &-c[1] \\ 0 & 1 & \dots & 0 & -c[2] \\ \vdots & \vdots & \ddots & & \vdots \\ 0 & 0 & \dots & 1 & -c[n-1] \end{pmatrix}.$$
You are not allowed to use Python `for`-loops, as they will make your function significantly slower for large $n$.

*Hint:* Concatenating NumPy arrays is often quite tricky. As an alternative, you can use NumPy arrays to access/define a set of indices of a NumPy array simultaneously. For example, `C[np.arange(n), np.arange(n)] = np.ones(n)` will set all diagonal elements of the $n \times n$ array `C` to $1$.
</div>

In [ ]:
def companion_matrix(c):
    """ assembles the matrix C """

    n = len(c)    # Length of input array

    # YOUR CODE HERE
    raise NotImplementedError()

Let's run your function through some basic tests to see if it works as expected.

In [ ]:
assert not (companion_matrix(np.ones(2)) is None), f"your function 'companion_matrix' returned nothing, make sure to 'return' your result"; assert isinstance(C := companion_matrix(np.ones(2)), np.ndarray), f"expected 'companion_matrix' to return a numpy array, but got {type(C)}"; assert (shape := companion_matrix(np.ones(2)).shape) == (2, 2), f"expected 'companion_matrix' to return a matrix of shape (2, 2), but got shape {shape}"; assert (C := companion_matrix(np.array([1]))) == (C_exp := np.array([[-1]])), f"'companion_matrix(np.array([1]))' should return \n {C_exp} \n but got \n {C}"; assert np.allclose(C := companion_matrix(np.array([1, 2, 3])), C_exp := np.array([[0, 0, -1], [1, 0, -2], [0, 1, -3]])), f"'companion_matrix(np.array([1, 2, 3]))' should return \n {C_exp} \n but got \n {C}"; print("Nice! Your function passes our tests.")

**Broadcasting** is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array. For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [8]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) # Create an empty matrix with the same shape as x
# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector `v` to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [9]:
vv = np.tile(v, (4, 1)) # Stack 4 copies of v on top of each other
print(vv) # Prints "[[1 0 1]
                   # [1 0 1]
                   # [1 0 1]
                   # [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [10]:
y = x + vv # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple
copies of `v`. Consider this version, using broadcasting

In [11]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `y = x + v` works even though `x` has shape (4, 3) and `v` has shape (3,) due to broadcasting; this line works as if `v` actually had shape (4, 3), where each row was a copy of `v`, and the sum was performed elementwise.
Broadcasting two arrays together follows these rules:
1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s
until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the
dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum
of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the
first array behaves as if it were copied along that dimension
Here are some applications of broadcasting:

In [12]:
# Compute outer product of vectors
v = np.array([1,2,3]) # v has shape (3,)
w = np.array([4,5]) # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [13]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
print(x + v)

[[2 4 6]
 [5 7 9]]


In [15]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it
where possible.

**Mathematical operations** with NumPy arrays are performed entrywise.

In [ ]:
X = np.diag([2, 2, 2])
Y = np.arange(1, 10).reshape(3, 3)
print(X)  # original array
print(Y)  # original array
print(X + Y)  # (entrywise) addition
print(X - Y)  # (entrywise) subtraction
print(X * Y)  # (entrywise) multiplication
print(X / Y)  # (entrywise) division
print(X % Y)  # (entrywise) modulus (remainder)
print(X ** Y)  # (entrywise) exponentiation

<div class="alert alert-info">

**Note:** `X`and `Y` do not need to have the same shape for these operations to work. The NumPy [broadcasting system](https://numpy.org/doc/stable/user/basics.broadcasting.html) will often appropriately adjust the shapes of both arrays for the operation to make sense.
</div>

In [ ]:
print(Y * 5)  # (entrywise) scalar multiplication
print(Y - np.array([1, 2, 3]))  # (row-wise) subtraction of vector from array

The same is valid for certain mathematical functions.

In [ ]:
print(np.sin(X))  # (entrywise) sine function
print(np.cos(X))  # (entrywise) cosine function
print(np.exp(X))  # (entrywise) exponential function
print(np.abs(X))  # (entrywise) absolute value function

A large collection of basic **linear algebra operations** are also available in NumPy.

In [ ]:
print(X @ Y)  # matrix-matrix multiplication
print(np.trace(X))  # trace
print(np.linalg.det(X))  # determinant
print(np.linalg.inv(X))  # inverse

<div class="alert alert-success">
    
**Exercise 3:** Given the vectors $x \in \mathbb{R}^n$ and $\mu \in \mathbb{R}^n$, and the matrix $\Sigma \in \mathbb{R}^{n \times n}$, compute the value of the *multivariate Gaussian PDF*
$$
f(x;\mu, \Sigma) = (2 \pi)^{-n/2} \det(\Sigma)^{-1/2} \exp\left(-\frac{1}{2} (x - \mu)^{\top} \Sigma^{-1} (x - \mu)\right).
$$

*Hint:* The NumPy variable `np.pi` gives a good approximation to $\pi$.
</div>

In [ ]:
def gaussian_pdf(x, mu, sigma):
    """ evaluates the multivariate Gaussian PDF with mean vector 'mu' and covariance matrix 'sigma' """

    n = len(x)

    # YOUR CODE HERE
    raise NotImplementedError()

Let's again do some tests to see if your implementation works correctly.

In [ ]:
assert not (gaussian_pdf(np.zeros(2), np.zeros(2), np.eye(2)) is None), f"your function 'gaussian_pdf' returned nothing, make sure to 'return' your result"; assert isinstance(f := gaussian_pdf(np.zeros(2), np.zeros(2), np.eye(2)), float), f"expected 'gaussian_pdf' to return a floating point number, but got {type(f)}"; assert np.allclose(f := gaussian_pdf(np.ones(2), np.zeros(2), np.eye(2)), f_exp := 1 / (2 * np.pi) * np.exp(-1)), f"'gaussian_pdf(np.ones(2), np.zeros(2), np.eye(2))' should return \n {f_exp} \n but got \n {f}"; assert np.allclose(f := gaussian_pdf(np.zeros(2), np.ones(2), np.array([[0, -1], [1, 0]])), f_exp := 1 / (2 * np.pi)), f"'gaussian_pdf(np.zeros(2), np.ones(2), np.array([[0, -1], [-1, 0]]))' should return \n {f_exp} \n but got \n {f}"; print("Good one! Your function returns the correct result on some basic tests.")

<hr style="clear:both">

### The `matplotlib` package for data visualization

For plotting, we will import the `pyplot` module from the `matplotlib` package.

In [ ]:
import matplotlib.pyplot as plt

Plotting with matplotlib is quite easy. Have a look at the following example of the function

$$ y(x) = \sin(5 x) \cos(x) + \sin(10 x) \cos(2 x) $$

evaluated at $100$ linearly spaced values in the interval $[-1, 1]$. 

In [ ]:
x = np.linspace(-1, 1, 100)
y = np.sin(5 * x) * np.cos(x) + np.sin(10 * x) * np.cos(2 * x)
plt.plot(x, y)
plt.show()

To make your plots easier to understand for others, particularly when plotting multiple curves simultaneously, we can add **labels**.

In [ ]:
x = np.linspace(-1, 1, 100)
y_1 = np.sin(5 * x) * np.cos(1 * x) + np.sin(10 * x) * np.cos(8 * x)
y_2 = np.sin(2 * x) * np.cos(3 * x) + np.sin(4 * x) * np.cos(2 * x)
y_3 = np.sin(1 * x) * np.cos(5 * x) + np.sin(2 * x) * np.cos(1 * x)
plt.plot(x, y_1, label="first curve")
plt.plot(x, y_2, label="second curve")
plt.plot(x, y_3, label="third curve")
plt.title("plot title")
plt.xlabel("x-axis label")
plt.ylabel("y-axis label")
plt.legend()
plt.show()

<div class="alert alert-success">
    
**Exercise 4:** Generate and plot *Lissajous curves* which are defined by the data
$$
\begin{cases} 
x_k = \cos(a t_k) \\
y_k = \sin(b t_k)
\end{cases}
$$
with $t_k = \frac{2 \pi k}{500}~\text{for}~k = 0, 1, \dots, 500$ and for $(a, b) = (7, 5)$ and $(5, 1)$. Make sure to label the two curves in a legend, name the $x$- and $y$-axes, and give your plot an appropriate title.
</div>

In [ ]:
t = np.linspace(0, 2 * np.pi, 501)

# YOUR CODE HERE
raise NotImplementedError()

<hr style="clear:both">

## The end

Congratulations! You have made it to the end of the first exercise notebook. 